version: '3.4'

services:
  marathonregistrationbackendpython:
    image: marathonregistrationbackendpython
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
