version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
