# Use an official Python runtime as the base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt /app/

# Install the dependencies specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY . /app/

# Set the environment variable for Flask app
ENV FLASK_APP=server_sqlite.py

# Expose the port that Flask will run on
EXPOSE 5000

# Define the command to run the Flask app using flask CLI
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
